export const sagaActions = {
    ADD_MOVIE: "ADD_MOVIE",
    EDIT_MOVIE: "EDIT_MOVIE",
    DELETE_MOVIE: "DELETE_MOVIE",
    FETCH_MOVIES: "FETCH_MOVIES",
    GET_MOVIE: "GET_MOVIE",
    SEARCH_MOVIES: "SEARCH_MOVIES",
    FILTER_MOVIES: "FILTER_MOVIES",
}
